export enum SocketEvent {
  Message = 'message',
  Notification = 'notification',
  ChannelJoin = 'channel:join',
  ChannelLeave = 'channel:leave',
  UserTyping = 'user:typing',
  MessageEdited = 'message:edited',
  MessageDeleted = 'message:deleted',
  ReactionAdded = 'reaction:added',
  UserPresence = 'user:presence',
  TaskUpdated = 'task:updated',
  AiAlert = 'ai:alert',
  MeetingHandRaised = 'participant:hand_raised',
  MeetingReaction = 'meeting:reaction',
  MeetingSpotlight = 'meeting:spotlight',
  MeetingRecordingStatus = 'meeting:recording_status',
  MeetingMuteAll = 'meeting:mute_all',
}
